# services:
#   namenode:
#     image: apache/hadoop:3.3.5
#     container_name: namenode
#     hostname: namenode
#     environment:
#       - CLUSTER_NAME=hadoop-cluster
#     ports:
#       - "9870:9870"
#       - "9000:9000"
#     volumes:
#       - hadoop_namenode:/hadoop/dfs/name
#     command: ["hdfs", "namenode"]
#     networks:
#       - hdfs_network

#   datanode:
#     image: apache/hadoop:3.3.5
#     container_name: datanode
#     environment:
#       - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
#     volumes:
#       - hadoop_datanode:/hadoop/dfs/data
#     command: ["hdfs", "datanode"]
#     depends_on:
#       - namenode
#     networks:
#       - hdfs_network

#   webapp:
#     build: ./app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - namenode
#       - datanode
#     environment:
#       - HDFS_HOST=namenode
#       - HDFS_PORT=9000
#     networks:
#       - hdfs_network

# networks:
#   hdfs_network:
#     driver: bridge

# volumes:
#   hadoop_namenode:
#   hadoop_datanode:


services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hdfs_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hdfs_network

  webapp:
    build: ./app
    container_name: webapp
    ports:
      - "5000:5000"
    depends_on:
      - namenode
      - datanode
    environment:
      - HDFS_HOST=namenode
      - HDFS_PORT=9870
    networks:
      - hdfs_network

  webapp2:
    build: ./app
    container_name: webapp2
    ports:
      - "5001:5000"
    depends_on:
      - namenode
      - datanode
    environment:
      - HDFS_HOST=namenode
      - HDFS_PORT=9870
    networks:
      - hdfs_network

networks:
  hdfs_network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode: